### PR TITLE
support newer ingress apiVersion

### PR DESCRIPTION
**Pull request by euven**
from K8s version 1.22 you can only access the ingress api via the stable `networking.k8s.io/v1` API

### CODE REVIEW

**Comment by euven** [comment]
@lewismc is it possible to backport this to the 1.26 version too?

**Comment by euven** [comment]
@lewismc I've made some more changes that'll allow you to backport this to 1.26.

This is ingress template is basically what you get when executing `helm create` ;)

**Comment by euven** [comment]
ping @lewismc - really keen to get this deployed! :)

**Comment by euven** [comment]
@lewismc can you at least let us know if this project is dead, so I can fork it for our organisation?

**Comment by lewismc** [comment]
Hi @euven sincere apologies. It is not dead I was on vacation for a month. I apologize.

I am going to work on granting all contributors commit rights to remove myself as the sole point of failure.

I'll review right now, hopefully merge and then make a release.

**Comment by lewismc** [comment]
@euven I pushed a release to [Artifactory](https://apache.jfrog.io/ui/native/tika/tika/) for 2.9.0 and 2.9.0-full.
If there's anything else you would like please let me know here.
Thanks

**Comment by euven** [comment]
Thank you very much @lewismc and apologies for all the pings while you were away on holiday (hope you enjoyed it!) - glad to hear this project is alive and well :)

**Pull request merged**
