### PR TITLE
2.9.2.0 release

### PR DESCRIPTION
**Pull request by tballison**
This is a draft to update the Tika version to 2.9.2. I don't know what I'm doing with helm. Please review

### CODE REVIEW

**Comment by lewismc** [comment]
Will revisit this ticket once we have closed out https://github.com/apache/tika-helm/pull/19

**Comment by aidanthewiz** [comment]
Any ETA on a release? @lewismc

**Comment by lewismc** [comment]
hi Aidan, Ive been on extended vacation and will roll a release upon my
return on 8th July.
sorry for the delay.

**Comment by aidanthewiz** [comment]
@lewismc 
Any news on a deployment? Could probably also go to `2.9.2.1-full` image and release 2.9.2.1 instead.

**Comment by quantranhong1999** [comment]
Hi, any update on the next release?

**Comment by tballison** [comment]
@lewismc dunno if you have any time, but we just released 3.0.0. I'm in the process of building and pushing 3.0.0's docker image on https://issues.apache.org/jira/browse/TIKA-4329 . 

It'd be great to have a 2.9.2 and a 3.0.0.

**Comment by lewismc** [comment]
Hi @aidanthewiz @quantranhong1999 @tballison I never saw these notifications until now. They were being filtered in my email. I really apologize. I will roll a release this weekend.
@tballison I will start a thread over on dev@ regarding extending commit rights to developers of the tika-helm chart. Me as the single point of failure is not sufficient.
Thanks for your patience everyone and I really apologize @aidanthewiz as you have been knocking on the door the longest.

**Comment by lewismc** [comment]
Closing this PR off. I am pushing the release right now.

**Pull request closed without merging**
